name: mec_attendance
description: An app for MECians to check their attendance.
version: 1.1.0+15

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gradient_app_bar: ^0.0.1
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  beautifulsoup: ^0.0.1
  shared_preferences: ^0.5.6+1
  retry: ^3.0.0+1
  url_launcher: ^5.1.3
  percent_indicator: ^2.1.1+1
  simple_animations: ^1.3.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2+1"

flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true


flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/mec.png


  # fonts:
  #     - family: poppins
  #       fonts:
  #         - asset: assets/fonts/Poppins-Regular.ttf
  #     - family: avenir
  #       fonts:
  #         - asset: assets/fonts/font.ttf

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
